version: "3"
services:
  php:
    build: .
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./api:/var/www/html
     - ./api/php.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
     - db
  db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=ecommerce
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 9898:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data: